### PR TITLE
Editing of the watch list

### PR DESCRIPTION
**Pull request by AlphonseJr**
@MathieuNls : This time, I think it's good :)

### CODE REVIEW

**Comment by MathieuNls** [comment]
You forgot to add `reconvilier` here: https://github.com/AlphonseJr/tw-watches/blob/master/watch-brand.json

**Review by MathieuNls — CHANGES_REQUESTED** [review]
You forgot to add reconvilier here: https://github.com/AlphonseJr/tw-watches/blob/master/watch-brand.json

**Comment by MathieuNls** [comment]
ping

**Comment by MathieuNls** [comment]
ping

**Comment by AlphonseJr** [comment]
it should be okay now @MathieuNls :)

**Review by MathieuNls — APPROVED** [review]

**Pull request merged**
